site_name: Llenguatge de marques
site_url: https://seicoll.github.io/gitbook-xml/
repo_url: https://github.com/seicoll/gitbook-xml

theme:
  name: material
  # logo: assets/js_icon.png
  # favicon: assets/js_icon.png

  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: white
      accent: blue
  font:
    text: Inter
    code: JetBrains Mono

plugins:
  - search

copyright: |
  © 2027 Sergi Coll  
   – Institut Bosc de la Coma

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

nav:
  - UNITAT 1. HTML I CSS:
      - Llenguatge HTML: 01-html-css/uf1_html.md
      - CSS: 01-html-css/uf1_css.md
      - Disseny responsiu: 01-html-css/responsive.md

  - UNITAT 2. Llenguatges de marques:
      - Introducció: 02-xml-json/intro.md
      - Markdown: 02-xml-json/markdown.md
      - XML: 02-xml-json/xml.md
      - JSON: 02-xml-json/json.md
      - Validació amb DTD: 02-xml-json/uf1_dtd.md
      - Validació amb XSD: 02-xml-json/uf1_xsd.md
      - Exercicis: 02-xml-json/exercicis.md

  # - UNITAT 3. Javascript i Sistemes de gestió empresarial:

